FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Render exposes the port in the PORT env variable dynamically,
# but we can set a default.
ENV PORT=7000
EXPOSE 7000

RUN npm run build

CMD ["npm", "start"]
